apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: coreserverdeployment1
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: coreserver
    spec:
      containers:
      - name: core-server
        image: vmdemoregistary.azurecr.io/newtrialforkubenetes:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: b61
